### ISSUE TITLE
SQLAlchemy Async error

### ISSUE THREAD

**Issue by theobouwman** [reagento/dishka#149]
Multiple Asynchronous sqlalchemy calls are not working properly with the following code, synchronous does.
I read that I need to have an `AsyncSession` per asyncio task. How could I instruct Dishka to handle this?

```python
class DBProvider(Provider):
    @provide(scope=Scope.APP)
    def engine(self) -> AsyncEngine:
        engine = create_async_engine(
            get_config().ASYNC_DB_URL(),
            echo=get_config().QUERY_ECHO,
            echo_pool=get_config().ECHO_POOL,
            pool_pre_ping=True,
            pool_size=get_config().DB_POOL_SIZE,
            json_serializer=custom_json_serialiser
        )
        return engine


    @provide(scope=Scope.REQUEST)
    async def session(self, engine: AsyncEngine) -> AsyncIterable[AsyncSession]:
        async with AsyncSession(engine, expire_on_commit=False) as session:
            yield session
```

Feed service:
```python
class FeedService:
    def __init__(self, feed_item_repository: FeedItemRepository) -> None:
        self._feed_item_repository: FeedItemRepository = feed_item_repository


    async def get_organisation_feed(self, organisation_id: str, page: int = None, size: int = 20) -> List[FeedItem]:
        return await self._feed_item_repository.get_for_organisation(organisation_id, page, size, load_all=True)
    

    async def get_organisations_feed(self, organisation_ids: List[str], page: int = None, size: int = 20) -> List[FeedItem]:
        feed_items = []
        
        async def get_organisation_feed_task(organisation_id):
            organisation_feed = await self.get_organisation_feed(organisation_id)
            for feed_item in organisation_feed:
                feed_items.append(feed_item)

        tasks = []
        for organisation_id in organisation_ids:
            tasks.append(asyncio.create_task(get_organisation_feed_task(organisation_id)))

        await asyncio.gather(*tasks)

        return feed_items
```

Feed Item repo:
```python
class FeedItemRepository(BaseRepository[FeedItem]):

    _model = FeedItem


    async def get_for_organisation(self, organisation_id: str, page: int = None, size: int = None, load_all: bool = False) -> list[FeedItem]:
        q = select(self._model).filter(self._model.organisation_id == organisation_id)

        if load_all:
            q = q.options(
                # joinedload(self._model.user),
                joinedload(self._model.organisation),
                joinedload(self._model.organisation),
                joinedload(self._model.event),
                joinedload(self._model.group),
                joinedload(self._model.message),
                joinedload(self._model.message_parent),
            )

        if page is not None and size is not None:
            q = q.limit(size).offset(page * size)

        q = q.order_by(self._model.created_at.desc())

        return (await self.session.execute(q)).scalars().unique().all()
```

When I call the `FeedService.get_organisations_feed` method it complains about this following:

```
Traceback (most recent call last):
  File "/Users/theobouwman/dev/projects/momo/momo-api/venv/lib/python3.11/site-packages/dishka/integrations/starlette.py", line 41, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/theobouwman/dev/projects/momo/momo-api/venv/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/theobouwman/dev/projects/momo/momo-api/venv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/theobouwman/dev/projects/momo/momo-api/venv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/theobouwman/dev/projects/momo/momo-api/venv/lib/python3.11/site-packages/starlette/routing.py", line 758, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/theobouwman/dev/projects/momo/momo-api/venv/lib/python3.11/site-packages/starlette/routing.py", line 778, in app
    await route.handle(scope, receive, send)
  File "/Users/theobouwman/dev/projects/momo/momo-api/venv/lib/python3.11/site-packages/starlette/routing.py", line 299, in handle
    await self.app(scope, receive, send)
  File "/Users/theobouwman/dev/projects/momo/momo-api/venv/lib/python3.11/site-packages/starlette/routing.py", line 79, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/Users/theobouwman/dev/projects/momo/momo-api/venv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/theobouwman/dev/projects/momo/momo-api/venv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/theobouwman/dev/projects/momo/momo-api/venv/lib/python3.11/site-packages/starlette/routing.py", line 74, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/theobouwman/dev/projects/momo/momo-api/venv/lib/python3.11/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/theobouwman/dev/projects/momo/momo-api/venv/lib/python3.11/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/theobouwman/dev/projects/momo/momo-api/venv/lib/python3.11/site-packages/dishka/integrations/base.py", line 161, in autoinjected_func
    return await func(*args, **kwargs, **solved)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/theobouwman/dev/projects/momo/momo-api/api/routes/me.py", line 475, in get_me_feed
    feed_items = await feed_service.get_organisations_feed(user.organisation_ids_permissions, page=page)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/theobouwman/dev/projects/momo/momo-api/common/services/feed_service.py", line 32, in get_organisations_feed
    await asyncio.gather(*tasks)
  File "/Users/theobouwman/dev/projects/momo/momo-api/common/services/feed_service.py", line 24, in get_organisation_feed_task
    organisation_feed = await self.get_organisation_feed(organisation_id)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/theobouwman/dev/projects/momo/momo-api/common/services/feed_service.py", line 17, in get_organisation_feed
    return await self._feed_item_repository.get_for_organisation(organisation_id, page, size, load_all=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/theobouwman/dev/projects/momo/momo-api/common/repositories/feed_item_repo.py", line 33, in get_for_organisation
    return (await self.session.execute(q)).scalars().unique().all()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/theobouwman/dev/projects/momo/momo-api/venv/lib/python3.11/site-packages/sqlalchemy/ext/asyncio/session.py", line 452, in execute
    result = await greenlet_spawn(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/theobouwman/dev/projects/momo/momo-api/venv/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 186, in greenlet_spawn
    result = context.switch(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/theobouwman/dev/projects/momo/momo-api/venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2306, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/theobouwman/dev/projects/momo/momo-api/venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2181, in _execute_internal
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/theobouwman/dev/projects/momo/momo-api/venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2050, in _connection_for_bind
    return trans._connection_for_bind(engine, execution_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in _connection_for_bind
  File "/Users/theobouwman/dev/projects/momo/momo-api/venv/lib/python3.11/site-packages/sqlalchemy/orm/state_changes.py", line 103, in _go
    self._raise_for_prerequisite_state(fn.__name__, current_state)
  File "/Users/theobouwman/dev/projects/momo/momo-api/venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 945, in _raise_for_prerequisite_state
    raise sa_exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: This session is provisioning a new connection; concurrent operations are not permitted (Background on this error at: https://sqlalche.me/e/20/isce)

During handling of the above exception, another exception occurred:

  + Exception Group Traceback (most recent call last):
  |   File "/Users/theobouwman/dev/projects/momo/momo-api/venv/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi
  |     result = await app(  # type: ignore[func-returns-value]
  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/Users/theobouwman/dev/projects/momo/momo-api/venv/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
  |     return await self.app(scope, receive, send)
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/Users/theobouwman/dev/projects/momo/momo-api/venv/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
  |     await super().__call__(scope, receive, send)
  |   File "/Users/theobouwman/dev/projects/momo/momo-api/venv/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
  |     await self.middleware_stack(scope, receive, send)
  |   File "/Users/theobouwman/dev/projects/momo/momo-api/venv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
  |     raise exc
  |   File "/Users/theobouwman/dev/projects/momo/momo-api/venv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
  |     await self.app(scope, receive, _send)
  |   File "/Users/theobouwman/dev/projects/momo/momo-api/venv/lib/python3.11/site-packages/starlette/middleware/cors.py", line 83, in __call__
  |     await self.app(scope, receive, send)
  |   File "/Users/theobouwman/dev/projects/momo/momo-api/venv/lib/python3.11/site-packages/starlette/middleware/gzip.py", line 24, in __call__
  |     await responder(scope, receive, send)
  |   File "/Users/theobouwman/dev/projects/momo/momo-api/venv/lib/python3.11/site-packages/starlette/middleware/gzip.py", line 44, in __call__
  |     await self.app(scope, receive, self.send_with_gzip)
  |   File "/Users/theobouwman/dev/projects/momo/momo-api/venv/lib/python3.11/site-packages/dishka/integrations/starlette.py", line 37, in __call__
  |     async with request.app.state.dishka_container(
  | dishka.exceptions.ExitError: Cleanup context errors (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/Users/theobouwman/dev/projects/momo/momo-api/venv/lib/python3.11/site-packages/dishka/async_container.py", line 157, in close
    |     await anext(exit_generator.callable)
    |   File "/Users/theobouwman/dev/projects/momo/momo-api/di.py", line 79, in session
    |     async with AsyncSession(engine, expire_on_commit=False) as session:
    |   File "/Users/theobouwman/dev/projects/momo/momo-api/venv/lib/python3.11/site-packages/sqlalchemy/ext/asyncio/session.py", line 1071, in __aexit__
    |     await asyncio.shield(task)
    |   File "/Users/theobouwman/dev/projects/momo/momo-api/venv/lib/python3.11/site-packages/sqlalchemy/ext/asyncio/session.py", line 1016, in close
    |     await greenlet_spawn(self.sync_session.close)
    |   File "/Users/theobouwman/dev/projects/momo/momo-api/venv/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 186, in greenlet_spawn
    |     result = context.switch(*args, **kwargs)
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/Users/theobouwman/dev/projects/momo/momo-api/venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2462, in close
    |     self._close_impl(invalidate=False)
    |   File "/Users/theobouwman/dev/projects/momo/momo-api/venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2531, in _close_impl
    |     transaction.close(invalidate)
    |   File "<string>", line 2, in close
    |   File "/Users/theobouwman/dev/projects/momo/momo-api/venv/lib/python3.11/site-packages/sqlalchemy/orm/state_changes.py", line 121, in _go
    |     raise sa_exc.IllegalStateChangeError(
    | sqlalchemy.exc.IllegalStateChangeError: Method 'close()' can't be called here; method '_connection_for_bind()' is already in progress and this would cause an unexpected state change to <SessionTransactionState.CLOSED: 5> (Background on this error at: https://sqlalche.me/e/20/isce)
````

**Comment by Tishka17** [comment]
You cannot use one session in multiple asyncio tasks

**Comment by theobouwman** [comment]
@Tishka17 yes i figured that out. Since I thought this is a common problem with async and dishka I thought that there would be a goto solution for this?

**Comment by Tishka17** [comment]
If you really need multiple sessions during one event processing you can change the scope for it. We have `Scope.ACTION` as nested for `Scope.REQUEST`, you can use it for session and then go deeper in scopes using your containers when you need it (maybe encapsulating logic in other objects or whatever):

```
with request_container() as action_container:
     session = action_container.get(Session)
```

`request_container` here is either `AsyncContainer` instance injected using framework integration or what was manually retrieved. The logic of scopes is pretty common (described in docs). As for now, I cannot see how to make it more convenient to use, I am open to suggestions

**Comment by Tishka17** [comment]
I am closing this issue. Feel free to open the new one if you have any proposals

**Comment by theobouwman** [comment]
Thanks. For example we do this now:

```python
@router.get('/get_organisations_feed')
@inject
async def get_feed(
    feed_service: Annotated[FeedService, FromDishka()],
    container: FromDishka[AsyncContainer],
):
    organisation_ids = [o['id'] for o in [
        {
            "id": "eb1e0914-37c1-4748-b754-48d4cdc8bb61"
        },
        {
            "id": "4965d7a6-0653-43a4-ac12-6149439d2683"
        },
        {
            "id": "1580acf2-03db-40b0-9418-8f38a3b549b2"
        },
        {
            "id": "db6d777a-430d-4194-9189-0da878d7ca08"
        },
        {
            "id": "e1383451-08e0-481b-9482-db4c879008c8"
        },
        {
            "id": "f1c06a44-16fc-4791-ba8d-f5a05b235538"
        }
        ]
    ]

    feed  = await feed_service.get_organisations_feed(organisation_ids, container=container)

    return {

    }
```

THen in the FeedService we pass the container:
```python

class FeedService:
    def __init__(self,
                feed_item_repository: FeedItemRepository,
                nats_service: NATSService
    ) -> None:
        self._feed_item_repository: FeedItemRepository = feed_item_repository
        self.nats_service = nats_service


    async def get_organisation_feed(self, organisation_id: str, page: int = None, size: int = 20) -> List[GetFeedItemResponse]:
        """
        get organisation feed from NATS cache or database
        """
        return await self._feed_item_repository.get_for_organisation(organisation_id, page, size, load_all=True)

     async def get_organisations_feed(
        self, 
        organisation_ids: List[str], 
        container: AsyncContainer,
        page: int = None,
    ) -> List[FeedItem]:
        tasks = []

        for organisation_id in organisation_ids:
            async with container() as action_container:
                session = action_container.get(AsyncSession)
                tasks.append(asyncio.create_task(self.get_organisation_feed(organisation_id)))

        return await asyncio.gather(*tasks)
```

And the FeedItemRepo is a subsclass of the BaseRepo:
```python

class BaseRepository(Generic[T]):
    _model: T # TODO: find out if this is best solution

    def __init__(self, session: AsyncSession):
        self.session = session



class FeedItemRepository(BaseRepository[FeedItem]):

    _model = FeedItem


    async def get(self, feed_item: FeedItem) -> FeedItem:
        q = select(self._model) \
            .filter(self._model.organisation_id == feed_item.organisation_id) \
            .filter(self._model.user_id == feed_item.user_id) \
            .filter(self._model.event_id == feed_item.event_id) \
            .filter(self._model.group_id == feed_item.group_id) \
            .filter(self._model.message_id == feed_item.message_id) \
            .filter(self._model.parent_message_id == feed_item.parent_message_id) \
            .filter(self._model.type == feed_item.type) \

        return (await self.session.execute(q)).scalar()


    async def get_for_organisation(self,
        organisation_id: str,
        page: int = None,
        size: int = None,
        load_all: bool = False,
        before: AwareDatetime | None = None,
        after: AwareDatetime | None = None,
        type: FeedItemType | None = None
    ) -> list[FeedItem]:
        q = select(self._model).filter(self._model.organisation_id == organisation_id)
.....
```

My code is not working as I am not sure how the `session` in the FeedItemRepository` gets replaces with an ACTION scope?

**Comment by Tishka17** [comment]
As I see, your FeedItemRepository and Session have scope REQUEST. 
But, you have multiple "Actions" running concurrently. That is the root of problem.

My suggestion is to change the scope to ACTION and modify service code like this:
```python
class FeedService:
    def __init__(self, nats_service: NATSService) -> None:
        self.nats_service = nats_service


    async def get_organisation_feed(self,
         feed_item_repository: FeedItemRepository,
         organisation_id: str, page: int = None, size: int = 20,
) -> List[GetFeedItemResponse]:
        return await feed_item_repository.get_for_organisation(organisation_id, page, size, load_all=True)

     async def get_organisations_feed(
        self, 
        organisation_ids: List[str], 
        container: AsyncContainer,
        page: int = None,
    ) -> List[FeedItem]:
        tasks = []

        for organisation_id in organisation_ids:
            async with container() as action_container:
                repo = action_container.get(FeedItemRepository)
                tasks.append(asyncio.create_task(self.get_organisation_feed(repo, organisation_id)))

        return await asyncio.gather(*tasks)
```
