### ISSUE TITLE
Dishka with FastAPI & Faststream 'State' object has no attribute 'dishka_container'

### ISSUE THREAD

**Issue by theobouwman** [reagento/dishka#177]
My FastStream with FastAPI integration now start successfully and handles messages. However when it handles a message it throws this error `'State' object has no attribute 'dishka_container'`:
```
2024-07-05 21:08:49,071 ERROR    - momo-worker-default | user.email.summary.send                     | 549ceb4c-2 - AttributeError: 'State' object has no attribute 'dishka_container'
Traceback (most recent call last):
  File "api/venv/lib/python3.11/site-packages/starlette/datastructures.py", line 699, in __getattr__
    return self._state[key]
           ~~~~~~~~~~~^^^^^
KeyError: 'dishka_container'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "api/venv/lib/python3.11/site-packages/faststream/broker/subscriber/usecase.py", line 338, in consume
    await h.call(
  File "api/venv/lib/python3.11/site-packages/faststream/broker/subscriber/call_item.py", line 172, in call
    raise e
  File "api/venv/lib/python3.11/site-packages/faststream/broker/subscriber/call_item.py", line 164, in call
    result = await call(message)
             ^^^^^^^^^^^^^^^^^^^
  File "api/venv/lib/python3.11/site-packages/faststream/broker/middlewares/base.py", line 73, in consume_scope
    await self.after_consume(err)
  File "api/venv/lib/python3.11/site-packages/faststream/broker/middlewares/base.py", line 54, in after_consume
    raise err
  File "api/venv/lib/python3.11/site-packages/faststream/broker/middlewares/base.py", line 64, in consume_scope
    result = await call_next(await self.on_consume(msg))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "api/venv/lib/python3.11/site-packages/faststream/opentelemetry/middleware.py", line 239, in consume_scope
    result = await call_next(msg)
             ^^^^^^^^^^^^^^^^^^^^
  File "api/venv/lib/python3.11/site-packages/faststream/broker/middlewares/base.py", line 73, in consume_scope
    await self.after_consume(err)
  File "api/venv/lib/python3.11/site-packages/faststream/broker/middlewares/base.py", line 54, in after_consume
    raise err
  File "api/venv/lib/python3.11/site-packages/faststream/broker/middlewares/base.py", line 64, in consume_scope
    result = await call_next(await self.on_consume(msg))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "api/venv/lib/python3.11/site-packages/faststream/utils/functions.py", line 53, in to_async_wrapper
    return await call_or_await(func, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "api/venv/lib/python3.11/site-packages/fast_depends/utils.py", line 48, in run_async
    return await cast(Callable[P, Awaitable[T]], func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "api/venv/lib/python3.11/site-packages/faststream/broker/fastapi/route.py", line 214, in real_consumer
    return await consume(stream_message, message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "api/venv/lib/python3.11/site-packages/faststream/broker/fastapi/route.py", line 263, in app
    raw_reponse = await run_endpoint_function(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "api/venv/lib/python3.11/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/api/venv/lib/python3.11/site-packages/dishka/integrations/base.py", line 147, in autoinjected_func
    container = container_getter(args, kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "api/venv/lib/python3.11/site-packages/dishka/integrations/fastapi.py", line 44, in <lambda>
    container_getter=lambda _, p: p[param_name].state.dishka_container,
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/api/venv/lib/python3.11/site-packages/starlette/datastructures.py", line 702, in __getattr__
    raise AttributeError(message.format(self.__class__.__name__, key))
AttributeError: 'State' object has no attribute 'dishka_container'
2024-07-05 21:08:49,076 INFO     - momo-worker-default | user.email.summary.send                     | 549ceb4c-2 - Processed
```

The `nats_router` is initialised as:
```python
_router = NatsRouter(
        get_config().NATS_SERVER_URL,
        user_credentials="./nats-production-momo-api.creds",
        error_cb=error_cb,
        middlewares=(
            NatsTelemetryMiddleware(
                tracer_provider=tracer_provider,
            ),
        )
    )
```

And the rest of the code
```python
import asyncio
from typing import Annotated
from fastapi import FastAPI
from fastapi.responses import ORJSONResponse
from faststream.nats import DeliverPolicy
from dishka.integrations.fastapi import FromDishka, inject, setup_dishka
from api.auth import firebase_initialization
from common.api import lifespan
from common.config import get_config
from common.exceptions.handlers import init_exception_handlers
from common.middleware import init_middleware
from common.observability import init_observability
from common.services.nats_service import MOMO_WORKER_DEFAULT, NATSService
from common.services.user_service import UserService
from di import make_container

from common.schemas.worker import UserEmailSummarySendPayload, UserEmailSummarySuccessPayload

container, _, nats_router = make_container()

_app = FastAPI(
    title="momo-worker",
    lifespan=nats_router.lifespan_context,
    docs_url=get_config().swagger_url(),
    redoc_url=get_config().redoc_url(),
    debug=get_config().DEBUG,
    default_response_class=ORJSONResponse,
)

_app.include_router(nats_router)

setup_dishka(container, _app)
init_observability("momo-tasks", _app)
init_exception_handlers(_app)
init_middleware(_app)
firebase_initialization()

@nats_router.subscriber(
    "scheduled.bimonthly.user.email.summary.send",
    stream=MOMO_WORKER_DEFAULT,
    max_workers=1,
    deliver_policy=DeliverPolicy.ALL,
)
@inject
async def handler(user_service: Annotated[UserService, FromDishka()]):
    users = await user_service.get_all_users()

    tasks = []

    for user in users:
        tasks.append(asyncio.create_task(nats_router.broker.publish(UserEmailSummarySendPayload(user_id=user.uid), "user.email.summary.send")))

    await asyncio.gather(*tasks)


@nats_router.subscriber(
    "user.email.summary.send",
    stream=MOMO_WORKER_DEFAULT,
    max_workers=10,
    deliver_policy=DeliverPolicy.ALL,
)
@nats_router.publisher(
    "user.email.summary.success",
    stream=MOMO_WORKER_DEFAULT,
)
@inject
async def handler(msg: UserEmailSummarySendPayload, user_service: Annotated[UserService, FromDishka()], nats_service: Annotated[NATSService, FromDishka()]):
    asyncio.sleep(0.1)
    return msg


@nats_router.subscriber(
    "user.email.summary.success",
    stream=MOMO_WORKER_DEFAULT,
    max_workers=10,
    deliver_policy=DeliverPolicy.ALL,
)
@inject
async def handler(msg: UserEmailSummarySuccessPayload):
    asyncio.sleep(0.1)
    return msg


app = _app
```

**Comment by Tishka17** [comment]
You need setup dishka on fastapi and faststream app separately.

**Comment by Tishka17** [comment]
Check this:

https://gist.github.com/Lancetnik/5ae1744b211c6872faf52f3a7b13b931

**Comment by theobouwman** [comment]
Great, thankyou!
