### ISSUE TITLE
Error with inject decorator in integrations

### ISSUE THREAD

**Issue by ApostolFet** [reagento/dishka#319]
Some integrations use a KEYWORD-ONLY argument to additional parameters, which can lead to an attribute order error when there are **kwargs in the function being decorated
I have reproduced this error in taskiq:
```py
import asyncio
import random

from taskiq import AsyncTaskiqTask, InMemoryBroker

from dishka import FromDishka, Provider, Scope, make_async_container
from dishka.integrations.taskiq import inject, setup_dishka, TaskiqProvider

provider = Provider(scope=Scope.REQUEST)
provider.provide(lambda: random.random(), provides=float)  # noqa: S311

broker = InMemoryBroker()


@broker.task
@inject
async def random_task(num: FromDishka[float], **kwargs: str) -> float:
    print(kwargs)
    return num + 1


async def main() -> None:
    container = make_async_container(provider, TaskiqProvider())
    setup_dishka(container, broker)
    await broker.startup()

    my_kwargs = {"key": "value"}
    task: AsyncTaskiqTask[float] = await random_task.kiq(**my_kwargs)
    result = await task.wait_result()
    print(result.return_value)  # noqa: T201

    await broker.shutdown()
    await container.close()


if __name__ == "__main__":
    asyncio.run(main())
```
This code causes the following error:
```
Traceback (most recent call last):
  File "/home/apostol_fet/projects/github/dishka-task-iq/my_app/task_iq_example.py", line 16, in <module>
    @inject
     ^^^^^^
  File "/home/apostol_fet/projects/github/dishka-task-iq/.venv/lib64/python3.12/site-packages/dishka/integrations/taskiq.py", line 80, in inject
    return wrap_injection(
           ^^^^^^^^^^^^^^^
  File "/home/apostol_fet/projects/github/dishka-task-iq/.venv/lib64/python3.12/site-packages/dishka/integrations/base.py", line 151, in wrap_injection
    auto_injected_func.__signature__ = Signature(  # type: ignore[attr-defined]
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/inspect.py", line 3050, in __init__
    raise ValueError(msg)
ValueError: wrong parameter order: variadic keyword parameter before keyword-only parameter
```
A similar error can occur in the following integrations if the framework allows **kwargs in handlers:
- aiogram
- task iq
- fastapi
- litestar
- telebot

To solve this problem, we can use VAR_KEYWORD for the kind of additional parameters OR write a function to add parameters in the right order.

**Comment by ApostolFet** [comment]
Fixed by adding the function to add parameters in the right order in #321
