### ISSUE TITLE
SqlAlchemy Async example

### ISSUE THREAD

**Issue by theobouwman** [reagento/dishka#35]
Do you happen to have a fastapi sqlalchemy async example to use this library with?

**Comment by Tishka17** [comment]
I am not sure about correct example but it might be like

```python
class MyProvider(Provider):
   @provide(scope=Scope.APP)
   def engine(self) -> Engine:
       return create_engine(url_object)


   @provide(scope=Scope.REQUEST)
   def session(self, engine: Engine) -> Iterable[AsyncSession]:
       async with AsyncSession(engine) as session:
        yield session


@router.get("/")
@inject
def index(session: Annotated[AsyncSession, Depends()]): ...
```

Note that here I use Depends imported from Dishka, nut the fastapi one. Anyway feel free to combine them if you feel necessary (fastapi Depends can be used for request decomposition, not only for DI)

**Comment by theobouwman** [comment]
app.py
```python
...
from dishka.integrations.fastapi import (
    Depends,
    inject,
    setup_dishka,
)


#
# app
#
app = FastAPI(docs_url=get_config().swagger_url(),
              redoc_url=get_config().redoc_url(), debug=get_config().DEBUG)
app.container = init_container()

container = make_async_container(MyProvider(get_config()))
setup_dishka(container, app)
...
```

database.py
```python


class MyProvider(Provider):
    def __init__(self, config: Config):
        self.config: Config = config

    @provide(scope=Scope.APP)
    def engine(self) -> AsyncEngine:
        engine = create_async_engine(
            self.config.ASYNC_DB_URL(),
            echo=True,
        )
        return engine


    @provide(scope=Scope.REQUEST)    
    async def session(self, engine: AsyncEngine) -> AsyncIterable[AsyncSession]:
        async with AsyncSession(engine) as session:
            yield session
```

and then this error:

```
/api/venv/lib/python3.11/site-packages/pydantic/_internal/_config.py:317: UserWarning: Valid config keys have changed in V2:
* 'anystr_strip_whitespace' has been renamed to 'str_strip_whitespace'
  warnings.warn(message, UserWarning)
Process SpawnProcess-7:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/local/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/api/venv/lib/python3.11/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/api/venv/lib/python3.11/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/api/venv/lib/python3.11/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/api/venv/lib/python3.11/site-packages/uvicorn/config.py", line 474, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/api/venv/lib/python3.11/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/api/api/app.py", line 28, in <module>
    container = make_async_container(MyProvider(get_config()))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/api/venv/lib/python3.11/site-packages/dishka/async_container.py", line 154, in make_async_container
    registries = make_registries(*providers, scopes=scopes)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/api/venv/lib/python3.11/site-packages/dishka/registry.py", line 73, in make_registries
    for source in provider.factories:
                  ^^^^^^^^^^^^^^^^^^
AttributeError: 'MyProvider' object has no attribute 'factories'
```

**Comment by Tishka17** [comment]
Sorry, my error. you need to call `super().__init__()`

**Comment by theobouwman** [comment]
thanks. I already figured it our. Ill close and open another question :)
